import { ref } from 'vue'

export const currentLang = ref('en')

export const setLanguage = (lang) => {
  currentLang.value = lang
}

export const translations = {
  en: {
    home: 'Home',
    about: 'About us',
    services: 'Services',
    gallery: 'Gallery',
    photos: 'Photos',
    videos: 'Videos',
    destinations: 'Destinations',
    kigali: 'Kigali City',
    northern: 'Northern province',
    southern: 'Southern province',
    western: 'Western province',
    eastern: 'Eastern province',
    contacts: 'Contacts',
    title: 'Discover the beauty of Rwanda',
    subtitle: 'Explore the wonders of Rwanda with our comprehensive travel guide.',
    btnExplore: 'Explore',
    btnLearn: 'Learn More',
    destTitle: 'Destinations',
    destDesc: 'Explore breathtaking volcanic landscapes, rolling hills, and vibrant cities.',
    wildTitle: 'Wildlife',
    wildDesc: 'Meet the majestic animals safely tucked in their natural habitat.',
    cultTitle: 'Culture',
    cultDesc: 'Experience rich traditional music, elegant dance, and local heritage.'
    ,
    servicesHeroTitle: 'Services built for your Rwanda journey',
    servicesHeroSubtitle: 'From safari planning and custom itineraries to local support and guided tours, our services make every trip to Rwanda unforgettable.',
    servicesCard1Title: 'Unforgettable Safaris',
    servicesCard1Desc: 'Experience nature at its finest with gorilla trekking, wildlife safaris, and expertly guided national park tours.',
    servicesCard2Title: 'Custom Packages',
    servicesCard2Desc: 'Tailored travel plans for families, adventure seekers, honeymooners, and culture fans.',
    servicesCard3Title: 'Local Assistance',
    servicesCard3Desc: 'Get support during your journey with local guides, transport help, and real-time travel advice.',
    galleryHeroTitle: 'Experience Rwanda through stunning visuals',
    galleryHeroSubtitle: 'Browse images and videos from the country’s most iconic landscapes, wildlife, and cultural moments.',
    galleryCard1Title: 'Volcanoes National Park',
    galleryCard1Desc: 'Venture deep into misty forests to stand face-to-face with rare mountain gorillas.',
    galleryCard2Title: 'Nyungwe Forest',
    galleryCard2Desc: 'Hike above ancient rainforest canopies and explore biodiverse trails filled with rare primates.',
    galleryCard3Title: 'Akagera National Park',
    galleryCard3Desc: 'Witness the Big Five roaming freely across expansive wetlands and savannah plains.',
    galleryCard4Title: 'Kigali City',
    galleryCard4Desc: 'Discover clean streets, vibrant art galleries, and a booming culinary scene.',
    galleryCard5Title: "King's Palace (Nyanza)",
    galleryCard5Desc: 'Journey south to Nyanza to experience rich traditions and historical architecture.',
    destinationsHeroTitle: 'Explore Rwanda’s most iconic destinations',
    destinationsHeroSubtitle: 'From city skylines to national parks, these are the locations you cannot miss.',
    destinationsCard1Title: 'City of Kigali',
    destinationsCard1Desc: 'The geographic heart and central gateway to every province.',
    destinationsCard2Title: 'Southern Interior',
    destinationsCard2Desc: 'Rolling hills, cultural sites, and historic heritage areas rich with local stories.',
    destinationsCard3Title: 'Eastern Border',
    destinationsCard3Desc: 'Expansive wetlands, lakes, and protected savannahs teeming with wildlife.',
    contactsHeroTitle: 'Reach out to our travel experts',
    contactsHeroSubtitle: 'We’re ready to help you plan an unforgettable Rwanda adventure with fast support.',
    contactsPageTitle: 'Contact Us',
    contactsPageDesc: 'Whether you need safari advice, booking help, or a local guide, connect with our team today.'
  },
  fr: {
    home: 'Accueil',
    about: 'À propos',
    services: 'Services',
    gallery: 'Galerie',
    photos: 'Photos',
    videos: 'Vidéos',
    destinations: 'Destinations',
    kigali: 'Ville de Kigali',
    northern: 'Province du Nord',
    southern: 'Province du Sud',
    western: 'Province de l\'Ouest',
    eastern: 'Province de l\'Est',
    contacts: 'Contacts',
    title: 'Découvrez la beauté du Rwanda',
    subtitle: 'Explorez les merveilles du Rwanda avec notre guide de voyage complet.',
    btnExplore: 'Explorer',
    btnLearn: 'En savoir plus',
    destTitle: 'Destinations',
    destDesc: 'Explorez des paysages volcaniques à couper le souffle, des collines naissantes et des villes vibrantes.',
    wildTitle: 'Faune',
    wildDesc: 'Rencontrez les majestueux animaux en toute sécurité dans leur habitat naturel.',
    cultTitle: 'Culture',
    cultDesc: 'Découvrez une musique traditionnelle riche, des danses élégantes et le patrimoine local.'
    ,
    servicesHeroTitle: 'Services conçus pour votre voyage au Rwanda',
    servicesHeroSubtitle: 'De la planification de safaris aux itinéraires personnalisés, nos services rendent chaque voyage inoubliable.',
    servicesCard1Title: 'Safaris inoubliables',
    servicesCard1Desc: 'Découvrez la nature avec le trekking des gorilles, les safaris animaliers et les visites guidées expertes.',
    servicesCard2Title: 'Forfaits personnalisés',
    servicesCard2Desc: 'Plans de voyage adaptés aux familles, aux aventuriers, aux lunes de miel et aux amateurs de culture.',
    servicesCard3Title: 'Assistance locale',
    servicesCard3Desc: 'Obtenez du soutien avec des guides locaux, le transport et des conseils de voyage en temps réel.',
    galleryHeroTitle: 'Découvrez le Rwanda en images',
    galleryHeroSubtitle: 'Parcourez des images et vidéos des paysages, de la faune et de la culture les plus emblématiques.',
    galleryCard1Title: 'Parc national des Volcans',
    galleryCard1Desc: 'Partez en forêt brumeuse pour voir des gorilles des montagnes rares.',
    galleryCard2Title: 'Forêt de Nyungwe',
    galleryCard2Desc: 'Marche au-dessus des canopées anciennes et découvrez des sentiers riches en biodiversité.',
    galleryCard3Title: 'Parc national d\'Akagera',
    galleryCard3Desc: 'Admirez les Big Five à travers les vastes zones humides et les plaines de savane.',
    galleryCard4Title: 'Ville de Kigali',
    galleryCard4Desc: 'Découvrez des rues propres, des galeries d\'art vibrantes et une scène culinaire florissante.',
    galleryCard5Title: 'Palais du Roi (Nyanza)',
    galleryCard5Desc: 'Voyagez vers le sud pour vivre des traditions riches et l\'architecture historique.',
    destinationsHeroTitle: 'Explorez les destinations emblématiques du Rwanda',
    destinationsHeroSubtitle: 'Des centres-villes aux parcs nationaux, ce sont les lieux à ne pas manquer.',
    destinationsCard1Title: 'Ville de Kigali',
    destinationsCard1Desc: 'Le cœur géographique du Rwanda et la porte d\'entrée centrale vers chaque province.',
    destinationsCard2Title: 'Intérieur sud',
    destinationsCard2Desc: 'Collines ondulantes, sites culturels et patrimoine historique riches en histoires locales.',
    destinationsCard3Title: 'Frontière est',
    destinationsCard3Desc: 'Zones humides, lacs et savanes protégées regorgeant de faune.',
    contactsHeroTitle: 'Contactez nos experts en voyage',
    contactsHeroSubtitle: 'Nous sommes prêts à vous aider à planifier une aventure inoubliable au Rwanda.',
    contactsPageTitle: 'Contactez-nous',
    contactsPageDesc: 'Besoin de conseils safari, d\'aide pour les réservations ou d\'un guide local ? Contactez notre équipe aujourd\'hui.'
  },
  rw: {
    home: 'Impuzu',
    about: 'Uko turi',
    services: 'Serivisi',
    gallery: 'Ifoto',
    photos: 'Ifoto',
    videos: 'Videyow',
    destinations: 'Ahantu',
    kigali: 'Umujyi wa Kigali',
    northern: 'Intara y\'Amajyaruguru',
    southern: 'Intara y\'Amajyaruguru',
    western: 'Intara y\'Iburengerazuba',
    eastern: 'Intara y\'Uburasirazuba',
    contacts: 'Ihorera',
    title: 'Vumbura ubwiza bw\'u Rwanda',
    subtitle: 'Sura ibitangaza by\'u Rwanda ukoresheje amakuru arambuye y\'urugendo rwacu.',
    btnExplore: 'Tembera',
    btnLearn: 'Menya Amakuru',
    destTitle: 'Ahantu hasurwa',
    destDesc: 'Sura ibirunga bitangaje, imisozi miremire, n\'imijyi ishabutse.',
    wildTitle: 'Inyamaswa',
    wildDesc: 'Sura inyamaswa zisanzuye mu ndiri yazo karemano.',
    cultTitle: 'Umuco',
    cultDesc: 'Inovore umuziki gakondo ukize, imbyino nziza, n\'umuco wacu w\'umwimerere.'
  },
  sw: {
    home: 'Nyumba',
    about: 'Kuhusu sisi',
    services: 'Huduma',
    gallery: 'Orodha ya picha',
    photos: 'Picha',
    videos: 'Video',
    destinations: 'Maeneo',
    kigali: 'Jiji la Kigali',
    northern: 'Jimbo la Kaskazini',
    southern: 'Jimbo la Kusini',
    western: 'Jimbo la Magharibi',
    eastern: 'Jimbo la Mashariki',
    contacts: 'Mawasiliano',
    title: 'Gundua uzuri wa Rwanda',
    subtitle: 'Gundua maajabu ya Rwanda kwa mwongozo wetu wa kina wa kusafiri.',
    btnExplore: 'Gundua',
    btnLearn: 'Jifunze Zaidi',
    destTitle: 'Maeneo',
    destDesc: 'Gundua mandhari ya kuvutia ya volkano, milima yenye upepo, na miji yenye nguvu.',
    wildTitle: 'Wanyamapori',
    wildDesc: 'Kutana wanyama adhimu walio salama katika makazi yao ya asili.',
    cultTitle: 'Utamaduni',
    cultDesc: 'Uzoefu wa muziki wa kitamaduni tajiri, ngoma za kifahari, na urithi wa wenyeji.'
  }
}
